services:
  chatroom-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app
    container_name: chatroom-service
    expose:
      - '8003'
    ports:
      - '8003:8003'
    depends_on:
      chatroom-service-postgres:
        condition: service_healthy
    links:
      - chatroom-service-postgres
  chatroom-service-postgres:
    container_name: chatroom-service-postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5