services:
  chatroom-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app
    container_name: chatroom-service
    expose:
      - '8003'
    ports:
      - '8003:8003'
    network_mode: "host"
  # chatroom-service-postgres:
  #   container_name: chatroom-service-postgres
  #   image: postgres
  #   restart: always
  #   # set shared memory limit when using docker-compose
  #   shm_size: 128mb
  #   expose:
  #     - '5433'
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5